PImage YoungModernF;
float posYdio;
String DioramaInfo;
PImage SchairGP;
PFont DioramaFuente;
String DioramaCnc;
PImage fnDiorama;
PImage DioramaFt;
String HistNB;
String CancionesNB;
PImage fondoNeon;
float tmnNeon;
int estado;
PImage imgintro;
String txt;
int contador; 
String txt2;
PImage imgDaniel;
float posX;
PImage imgBenuno;
float posY;
PImage imgChrisUno;
float posXchris;
PFont fuenteUno;
PImage imgfondoUno;
float fondoX;
float velFU;
PImage Frogstomp;
String FrogstompList;
PFont Setlist;
String FrogsHist;
PImage FondoRanas;
PImage Freak;
String FreakList;
PFont FreakFont;
PImage FondoFreak;
float fondoY;
String FreakInfo;
PImage DanielFreak;
PImage NeonBallroom;
float posXym;
PImage fondoModern;
String ListaYM;
String HistoriaYM;
float posYym;
PImage Reinicio;
String ReinicioT;
PFont ReinicioF;
 int  posYb;
 int posXymb;
 int posYneon;
 int posXi;
 int posXneonlista;
 int posXymd;
void setup(){
  ReinicioF=loadFont("clic.vlw");
  posXymd = 0;
  posXi=0;
  posYb = 340;
  posXymb = -200;
 posYneon = 640;
 int posXneonlista = 0;
size(640, 480);
ReinicioT = "¡Haz clic en los ojos para reiniciar!";
HistoriaYM = "Young Modern nació en el 2007, un momento extraño e introspectivo para Daniel Johns.\nDespués de años viviendo bajo la presión mediática y sintiéndose atrapado por la imagen\npública de la banda, comenzó a escribir canciones mucho más personales, elegantes\ny teatrales, casi como una forma de reinventarse. El disco refleja esa necesidad de escapar,\ncrecer y volver a disfrutar de hacer música, mezclando ansiedad, romanticismo  y\nuna sensación constante de cambio. El título “Young Modern” habla de esa idea: ser joven\npero sentirse desconectado de lo que se espera de vos.";
ListaYM = "1 -       Young Modern Station\n2 -       Straight Lines\n3 -       If You Keep Losing Sleep\n4 -       Reflections of a Sound\n5 -       Thieving Birds, Pt.1/Strange Behaviour/\n           Those Thieving Birds, Pt.2\n6 -       The Man That Knew Too Much\n7 -       Waiting All Day\n8 -       Mind Reader\n9 -       Low\n10 -     Insomnia\n11 -      All Across the World";
fondoModern = loadImage("fondoModern.png");
posXym = 0;
YoungModernF = loadImage("YoungModernF.jpg");
fondoNeon = loadImage("NeonB.png");
DanielFreak = loadImage ("DanielFreak.png");
FreakInfo = "Con solo 17 años, grabó en 1996\nsu segundo álbum Freak Show\nbajo la presión de la fama repentina.\nInfluenciados por la frustración de sentirse\ntratados como “bichos raros” por la industria,\nDaniel Johns escribió un disco más oscuro, pesado y agresivo.\nProducido por Nick Launay y lanzado en febrero de 1997,\nel álbum debutó en el #1 en Australia,\nvendió más de un millón y medio de copias\nLa portada con “Lobster Boy” refleja\nel concepto de circo de fenómenos que sentía la banda";
FondoFreak = loadImage("FondoFreak3.jpg");
FreakFont = loadFont ("FreakFont3.vlw");
FreakList = "1 - Slave\n2 - Freak\n3 - Abuse Me\n4 - Lie to Me\n5 - No Association\n6 - Cemetery\n7 - The Door\n8 - Pop Song for Us Rejects\n9 - Learn to Hate\n10 - Petrol & Chlorine\n11 - Roses\n12 - Nobody Came\n13 - The Closing";
Freak = loadImage("Freak.jpg");
FondoRanas = loadImage("FondoFrog2.jpg");
Setlist = loadFont("Setlist.vlw");
FrogsHist = "- Frogstomp fue grabado en solo\n9 días durante las vacaciones escolares\n\n- Lanzado el 27 de marzo de 1995\n\n- Los miembros tenían apenas 15 años y\naún asistían a la escuela secundaria\n\n- Presupuesto de aprox $40,000";
FrogstompList = "1 - Israel's Son\n2 - Tomorrow\n3 - Faultline\n4 - Pure Massacre\n5 - Shade\n6 - Leave me out\n7 - Suicidal dream\n8 - Madman\n9 - Undecided\n10 - Cicada\n11 - Findaway\n\nBonus tracks:\n1 - Tomorrow (Single Version)\n2 - Acid Rain\n3 - Blind\n4 - Stoned\n5 - Madman (Vocal Version)";
Frogstomp = loadImage("frogstomp.jpg");
imgfondoUno = loadImage("fondoPrimero.jpg");
imgintro = loadImage("youngmodern.jpg");
imgDaniel = loadImage("danielpnguno.png");
txt = "PLAY";
Reinicio = loadImage("Reinicio.jpg");
txt2 = "Silverchair\nLa banda se formó en 1992 en Newcastle, Australia,\nVocalista y Guitarrista: Daniel Johns. \nBaterista: Ben Gillies. \nBajista: Chris Joannou.\nSe conocieron en la escuela primaria. A partir de ahí,\ncrearon música en el garaje de la casa de los Johns,\nlo que les llevó a conseguir un contrato discográfico con Sony Music.";
contador++;
posYym = 600;
posX = 0;
posY = 0;
posXchris = 0;
imgBenuno = loadImage("BenG.png");
imgChrisUno = loadImage("ChrisPagUno.png");
fuenteUno = loadFont("fuenteSchair.vlw");
NeonBallroom = loadImage("NeonBallroom.jpg");
tmnNeon = 0;
CancionesNB = "1 - Emotion Sickness\n\n2 - Anthem for the Year 2000\n\n3 - Ana's Song (Open Fire)\n\n4 - Spawn (Again)\n\n5 - Miss You Love\n\n6 - Dearest Helpless\n\n7 - Do You Feel The Same\n\n8 - Black Tangled Heart\n\n9 - Point of View\n\n10 - Satin Sheets\n\n11 - Paint Pastel Princess\n\n12 - Steam Will Rise";
HistNB = "Para su tercer álbum\nen 1998, con 19 años,\nSilverchair entró\nal estudio con Nick\nLaunay para crear\nNeon Ballroom, un disco\nmucho más maduro,\nexperimental y orquestal\nque marcó\nuna clara evolución\nlejos del sonido\ngrunge de sus\nprimeros trabajos.\nLanzado en\nmarzo de 1999,\ndebutó en el #1\nen Australia\ny fue certificado\nmultiplatino,\nconsolidándose como\nel álbum donde la banda\nlogró sonar\nrealmente como\nellos mismos,\nexplorando temas\npersonales profundos con\narreglos más\ncomplejos y emotivos.";
DioramaFt = loadImage("Diorama.jpg");
fnDiorama = loadImage("fondoDiorama1.png");
DioramaCnc = "1 - Across the Night\n2 - The Greatest View\n3 - Without You\n4 - World Upon Your Shoulders\n5 - One Way Mule\n6 - Tun in the Brine\n7 - Too Much of Not Enough\n8 - Luv Your Life\n9 - The Lever\n10 - My Favourite Thing\n11 - After All These Years";
DioramaFuente = loadFont("Diorama2.vlw");
SchairGP = loadImage("SchairFacha.png");
DioramaInfo = "Diorama, el quinto disco de Silverchair fue\nlanzado en el 2002. Marcó un antes\ny un después en su rumbo musical, se alejaron\ncompletamente del grunge para componer\nun rock psicodélico que avanzaba junto con la\nmadurez de sus integrantes. Un disco ambicioso y sofisticado\nmelódicamente que fue un éxito\ntanto en Australia como con su propio público.";
posYdio = -200;
}
